/**
 * 普通接口
 * @type {{taskCateList: string, taskCateAdd: string, taskCateInfo: string, taskProjectCateUpdate: string, taskCateUpdate: string, taskTypeUpdate: string, getNorms: string, addNorm: string, deleteNorm: string, getIconList: string, insideAudit: string, clientAudit: string, projectTaskTypeIndex: string, specificationLibraryIndex: string, companyProjectIndex: string, demandContractIndex: string, demandContractInfoIndex: string, outsourceContractInfoIndex: string, newTaskMemberList: string, getTaskTypeList: string, getProjectSchedule: string, getMemberList: string, getComponentDate: string, componentSchedulePrice: string, memberTaskSchedule: string, getMemberTaskSchedule: string, taskTypeTaskCount: string, getTaskCount: string, taskProjectUpdate: string, getTaskProjectInfo: string, projectTaskList: string, projectTaskInfo: string, taskStageInfo: string, taskProjectPage: string, taskTaskList: string, getProjectInfo: string, getStageInfo: string, accessoryUpload: string, getInfoRole: string, detailInfoRole: string, getAuthMenu: string, getAuthTable: string, mateExcel: string, addBatch: string, addMember: string, getCommonTaskList: string, getTaskDetailInfo: string, getTestTaskInfo: string, getTestInfo: string, stageUpload: string, getTestTaskBidInfo: string, getCompanyUserList: string, setRelatedUser: string, uploadTestHttp: string, AuditTestTaskList: string, getTestTaskLog: string, testTaskUpLoad: string, getBidList: string, postBaoJia: string, getTaskDetail: string, getTaskHall: string, choiceBidPrice: string, getWinBid: string, payToYi: string, collect: string, getTaskTaskStage: string, addCollaborationMember: string, delCollaborationMember: string, sendNotice: string, getCompanyInfo: string, companyMemberWork: string, companyProjectWork: string, companyTaskWork: string, companyTestTaskWork: string, companyContractWork: string, contractList: string, companyWorkCompany: string, companyFreeTrend: string, companyWorkIndex: string, updateCompanyInfo: string, getConfirmInfo: string, getCompanyConfirm: string, getCompanyCodeConfirm: string, getBankInfo: string, getCompanyAccount: string, getSignSigner: string, getSignerList: string, setOperator: string, getOperatorList: string, delOperator: string, getDepartmentList: string, getContractList: string, getSelectInfo: string, addCollaboration: string, collaborationList: string, deleteCollaboration: string, updateCollaboration: string, getConfirmContract: string}}
 */
import {onlyAPI} from './apiConfig.js';
const generalPaths = {
    aa: onlyAPI.file_upload_cert,
    systemNoticeNum: onlyAPI.system_notice_num,
    taskCateList: onlyAPI.task_cate_list,
    taskCateAdd: onlyAPI.task_cate_add,
    taskCateInfo: onlyAPI.task_task_typeinfo,
    taskProjectCateUpdate: onlyAPI.task_project_tasktypeupdate,
    taskCateUpdate: onlyAPI.task_cate_update,
    taskTypeUpdate: onlyAPI.task_task_typeupdate,
    getNorms: onlyAPI.task_norms,
    addNorm: onlyAPI.task_add_norm,
    deleteNorm: onlyAPI.task_delete_norm,
    getIconList: onlyAPI.task_icon_list,
    insideAudit: onlyAPI.task_inside_audit,
    clientAudit: onlyAPI.task_client_audit,
    projectTaskTypeIndex: onlyAPI.project_project_tasktypeindex,
    specificationLibraryIndex: onlyAPI.company_specification_libraryindex,
    companyProjectIndex: onlyAPI.company_projectindex,
    demandContractIndex: onlyAPI.company_demand_contractindex,
    demandContractInfoIndex: onlyAPI.company_demand_contract_infoindex,
    outsourceContractInfoIndex: onlyAPI.company_outsource_contractindex,
    newTaskMemberList: onlyAPI.project_membermember_list,
    getTaskTypeList: onlyAPI.task_task_typelist,
    getProjectSchedule: onlyAPI.company_project_scheduleproject_schedule,
    getMemberList: onlyAPI.task_member_list,
    getComponentDate: onlyAPI.company_datelist,
    // componentSchedulePrice: onlyAPI.company_contract_price_task,
    componentSchedulePrice: onlyAPI.system_create_task,
    memberTaskSchedule: onlyAPI.company_member_task_schedule,
    getMemberTaskSchedule: onlyAPI.task_member_task_schedule,
    taskTypeTaskCount: onlyAPI.task_get_tasktype_task_count,
    getTaskCount: onlyAPI.task_task_count,
    taskProjectUpdate: onlyAPI.task_projectupdate,
    getTaskProjectInfo: onlyAPI.task_info,
    projectTaskList: onlyAPI.task_project_tasktypelist,
    projectTaskInfo: onlyAPI.task_project_tasktypeinfo,
    taskStageInfo: onlyAPI.task_stage_info,
    taskProjectPage: onlyAPI.task_page,
    taskTaskList: onlyAPI.task_tasklist,
    getProjectInfo: onlyAPI.task_project_info,
    getStageInfo: onlyAPI.task_stage_info,
    accessoryUpload: onlyAPI.task_taskupdate,
    getInfoRole: onlyAPI.system_info,
    detailInfoRole: onlyAPI.page_init,
    getAuthMenu: onlyAPI.system_menu2,
    getAuthTable: onlyAPI.system_get_menu_table,
    mateExcel: onlyAPI.task_mate_excel,
    addBatch: onlyAPI.task_batch_add,
    addMember: onlyAPI.system_member_add,
    getCommonTaskList: onlyAPI.task_taskshaft,
    getTaskDetailInfo: onlyAPI.task_taskinfo,
    getTestTaskInfo: onlyAPI.task_bid_info,
    getTestInfo: onlyAPI.task_testinfo,
    stageUpload: onlyAPI.task_stage_upload,
    getTestTaskBidInfo: onlyAPI.task_testbid_info,
    getCompanyUserList: onlyAPI.task_member_page,
    setRelatedUser: onlyAPI.task_set_work_user,
    uploadTestHttp: onlyAPI.task_test_upload,
    AuditTestTaskList: onlyAPI.task_audit_list,
    getTestTaskLog: onlyAPI.task_bid_log,
    testTaskUpLoad: onlyAPI.task_testinside_audit,
    getBidList: onlyAPI.task_testbid_list,
    postBaoJia: onlyAPI.task_testjoin_test,
    getTaskDetail: onlyAPI.task_test_info,
    getTaskHall: onlyAPI.task_test_hall,
    choiceBidPrice: onlyAPI.task_choice_bid_price,
    getWinBid: onlyAPI.task_win_bid,
    payToYi: onlyAPI.task_pay,
    collect: onlyAPI.task_confirm_receipt,
    getTaskTaskStage: onlyAPI.task_task_stage,
    addCollaborationMember: onlyAPI.system_collaboration_member_add,
    delCollaborationMember: onlyAPI.system_collaboration_member_del,
    sendNotice: onlyAPI.task_notice,
    /**
     * 公司
     */
    getCompanyInfo: onlyAPI.task_company_info,
    companyMemberWork: onlyAPI.workbench_member_work,
    companyProjectWork: onlyAPI.workbench_working_project,
    companyTaskWork: onlyAPI.workbench_working_task,
    companyTestTaskWork: onlyAPI.workbench_working_bid_test,
    companyContractWork: onlyAPI.workbench_working_contract,
    contractList: onlyAPI.task_get_contract_list,
    companyWorkCompany: onlyAPI.workbench_company,
    companyFreeTrend: onlyAPI.workbench_member_free_trend,
    companyWorkIndex: onlyAPI.workbench_group_workindex,
    updateCompanyInfo: onlyAPI.task_update_company_info,
    getConfirmInfo: onlyAPI.system_confirm_info,
    getCompanyConfirm: onlyAPI.system_company_confirm,
    getCompanyCodeConfirm: onlyAPI.system_company_code_confirm,
    getBankInfo: onlyAPI.system_bank_info,
    getCompanyAccount: onlyAPI.system_company_account,
    getSignSigner: onlyAPI.system_signer,
    getSignerList: onlyAPI.system_signer_list,
    setOperator: onlyAPI.system_operator,
    getOperatorList: onlyAPI.system_operator_list,
    delOperator: onlyAPI.system_operator_del,
    getDepartmentList: onlyAPI.task_list,
    getContractList: onlyAPI.task_projectget_contract_list,
    getSelectInfo: onlyAPI.system_select_info,
    addCollaboration: onlyAPI.system_add_collaboration,
    collaborationList: onlyAPI.system_collaboration_list,
    deleteCollaboration: onlyAPI.system_delete_collaboration,
    updateCollaboration: onlyAPI.system_update_collaboration,
    /**
     * 合同
     */
    getConfirmContract: onlyAPI.task_confirm_contract,
};
/**
 * 引导
 * @type {{getAddProjectGuide: string, bubbleMyTask: string, bubbleResource: string, bubbleDownload: string, bubbleTeamwork: string, bubbleSchedule: string, bubbleMessage: string, bubbleChat: string, bubbleProjectHelper: string, bubbleFinance: string, bubbleFinanceList: string, bubbleTaskManage: string, bubbleGetMembers: string, bubbleProjectSchedule: string, bubbleReviseSchedule: string, bubbleAddFile: string, bubbleTaskProject: string}}
 */
const guidePaths = {
    getAddProjectGuide: onlyAPI.project_add_guide_index,
    bubbleMyTask: onlyAPI.system_wk_my_task,
    bubbleResource: onlyAPI.workbench_resource_index,
    bubbleDownload: onlyAPI.project_task_downloadindex,
    bubbleTeamwork: onlyAPI.worlbench_teamwork_index,
    bubbleSchedule: onlyAPI.system_wk_schedule,
    bubbleMessage: onlyAPI.system_message,
    bubbleChat: onlyAPI.system_chat,
    bubbleProjectHelper: onlyAPI.company_projectindex,
    bubbleFinance: onlyAPI.company_financelist,
    bubbleFinanceList: onlyAPI.company_finance_listindex,
    bubbleTaskManage: onlyAPI.company_finance_listindex,
    bubbleGetMembers: onlyAPI.project_team_workindex,
    bubbleProjectSchedule: onlyAPI.company_project_schedule_helperindex,
    bubbleReviseSchedule: onlyAPI.company_revise_scheduleindex,
    bubbleAddFile: onlyAPI.project_file_guide_index,
    bubbleTaskProject: onlyAPI.project_task_listindex,
    guideTestIndex:onlyAPI.company_testindex,
    memberGuideIndex:onlyAPI.system_index,
    demandContractInfo:onlyAPI.company_demand_contract_infoindex,
    outsourceContractInfo:onlyAPI.company_outsource_contract_infoindex
};


export default {
    generalPaths,
    guidePaths
};
