# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('bpub_date', models.DateField(verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('bread', models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf')),
                ('bcomment', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u91cf')),
                ('is_delete', models.BooleanField(default=False, verbose_name='\u903b\u8f91\u5220\u9664')),
            ],
            options={
                'db_table': 'tb_books',
                'verbose_name': '\u56fe\u4e66',
                'verbose_name_plural': '\u56fe\u4e66',
            },
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('hgender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='\u6027\u522b')),
                ('hcomment', models.CharField(max_length=200, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
                ('is_delete', models.BooleanField(default=False, verbose_name='\u903b\u8f91\u5220\u9664')),
                ('hbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.BookInfo', verbose_name='\u56fe\u4e66')),
            ],
            options={
                'db_table': 'tb_heros',
                'verbose_name': '\u82f1\u96c4',
                'verbose_name_plural': '\u82f1\u96c4',
            },
        ),
    ]
